### ISSUE TITLE
`cimgui.dll` is linked against a debug redistributable

### ISSUE THREAD

**Issue by GrimMaple** [Inochi2D/bindbc-imgui#10]
![cimgui](https://user-images.githubusercontent.com/10130860/147098022-f9b4f8eb-bd24-4146-8c3e-358df713c6ee.png)
Dependency Walker suggests that CIMGUI.DLL redistributed with `bindbc-imgui` is linked against debug VC++ runtime. This causes a lot of issues, as expected. I think it should be built and linked against a "release" VC++ runtime

**Comment by playmer** [comment]
Yeah this is currently a manual process, so it's very easy for one of us (almost certainly always me) to slip when we're debugging Inochi and committing a debug build, we really need all the binaries to be generated and committed as a GitHub Action rather than from our dev machines. Ideally it'd actually be uploaded as a Release, but I don't know _anything_ about how the D package manager works and if it can grab stuff from there. @LunaTheFoxgirl set that stuff up.

**Comment by playmer** [comment]
Please take a look to make sure the newest release looks right. I did check myself using [Dependencies](https://github.com/lucasg/Dependencies) (which I would recommend over Dependency Walker these days), but it's possible there's still an issue there.

**Comment by GrimMaple** [comment]
> Please take a look to make sure the newest release looks right. I did check myself using [Dependencies](https://github.com/lucasg/Dependencies) (which I would recommend over Dependency Walker these days), but it's possible there's still an issue there.

Dub hadn't quite yet registered the package update, though cloning the repo and using a local dependency works as expected now. I had some issues with `freetype.dll` not being copied over, but I'll have to see that once dub recognizes there's a new version. Thank you for a quick fix!

**Comment by playmer** [comment]
Of course, please let us know if you see an issue with freetype. I can't promise I can figure it out but I can try :) I'm also going to try to figure out the CI thing, but I might have to wait until this weekend if I can't figure out how to make commits from the CI.

And like I said, sorry for the trouble here. I'd say we still kinda have a lot in flux, but _ideally_ we don't make errors like this going forward at least.

**Comment by GrimMaple** [comment]
I have tested the `0.6.1` release on a fresh dub project and everything works perfectly, Thank you again :)
